### ISSUE TITLE
Determine methods for identifying active files in Text Class

### ISSUE THREAD

**Issue by njaffer** [mlibrary/objectclass#4]
files that are in the active collection and are related by identifier; some are not actually used; document all of the ways that we could check activeness (for the initial test colls --- amverse)

**Comment by cmkpowell** [comment]
Using Jeremy's Big Think, we use the xml output of the DLXS CGI to gather key pieces of information that are generated by the middleware. Including identification of active files--- this is as “right” as we can get, and has been subject to much public use. We use to fulltext view page with the debug=xml switch and collect the DLPSTEXTCLASS within the DocContent, following any image links to collect illustrations, etc.
