### ISSUE TITLE
Correspondence to IDs in other systems like Aleph for current metadata

### ISSUE THREAD

**Issue by njaffer** [mlibrary/objectclass#5]
tombstone table; bc we might have fresher metadata in aleph; and some things were digitized under aleph, and somethings notis; for any dlpsid, notis or aleph, we should be able to find records that relate to it, or at least IDs in the 001, 035.

**Comment by cmkpowell** [comment]
Variant versions of metadata as shown in the attached XML file.
[dmd.xml.txt](https://github.com/mlibrary/objectclass/files/1252825/dmd.xml.txt)

Give Tim a list of NOTIS IDs, get Aleph IDs and other identifiers to do this for all the items,
